### ISSUE TITLE
それゆけワンダーランド

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#11]
■ MP3所在位置
https://www.dropbox.com/s/crprsowfanio0hp/%E3%81%9D%E3%82%8C%E3%82%86%E3%81%91%E3%83%AF%E3%83%B3%E3%83%80%E3%83%BC%E3%83%A9%E3%83%B3%E3%83%89.mp3?dl=0

**Comment by lupan2525** [comment]
作業完了しました　Closeします
