### ISSUE TITLE
亡霊の女の子

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#13]
■ MP3所在位置
https://www.dropbox.com/s/8so35sh0vycv0v1/%E6%98%8E%E3%81%8F%E3%82%8B%E6%97%A5%E3%81%AE%E5%BF%98%E5%8D%B4.mp3?dl=0

**Comment by lupan2525** [comment]
お疲れ様ですLupanです、作業完了しました、Closeします
