### ISSUE TITLE
日々を彩るもの

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#14]
■ MP3所在位置
https://www.dropbox.com/s/lqk0v369gcrx3o8/%E6%97%A5%E3%80%85%E3%82%92%E5%BD%A9%E3%82%8B%E3%82%82%E3%81%AE.mp3?dl=0

**Comment by lupan2525** [comment]
お疲れ様ですLupanです、作業完了しました、Closeします
