### ISSUE TITLE
空を見上げれば

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#16]
■ MP3所在位置
https://www.dropbox.com/s/kqew5mple1unp48/%E7%A9%BA%E3%82%92%E8%A6%8B%E4%B8%8A%E3%81%92%E3%82%8C%E3%81%B0.mp3?dl=0

**Comment by lupan2525** [comment]
お疲れ様ですLupanです、作業完了しました、Closeします
