### ISSUE TITLE
ポチとLupanさんのセッションで利用するBGMを追加してください

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#161]
- TENSHI NI HEARTBREAK
- ぜろ
- 02 ピンボケ世怪平和
- 01 Chase Me

**Comment by lupan2525** [comment]
お疲れ様ですLupanですちょっと無理そうなのでBGM追加お願いします

**Comment by mc-Genius** [comment]
お疲れ様です。

**Comment by mc-Genius** [comment]
@lupan2525 さん、お疲れ様です。

@mc-Genius です。

ちょっと、無理そうなのでBGM追加をお願いします。

**Comment by mc-Genius** [comment]
BGM追加終了しました。クローズします。
