### ISSUE TITLE
絵コンテ追加の依頼

### ISSUE THREAD

**Issue by lupan2525** [stcg-document/STCG-Dev-Page#162]
お疲れ様ですLupanです、次元大介、石川五右衛門、峰不二子、エンゾ・ブロン、八咫烏 五郎
アルベール・ダンドレジー、の立ち絵の追加お願いします

**Comment by lupan2525** [comment]
追記パート4とパート5からでお願いします

**Comment by gooozudo** [comment]
入れました、クローズします。
