### ISSUE TITLE
重要キャラ追加について

### ISSUE THREAD

**Issue by gooozudo** [stcg-document/STCG-Dev-Page#203]
#### 対象キャラ
- マッスル・ゴーズド・マッサージ

#### 使用テーマ
- 超重武者

 設定
---
- サユキ、アリベルト、間島と並ぶ 「N/ストライガ」の幹部であるが、決闘の腕は他の３人よりも劣っている。
また、エーヴからは他のメンバーが様々なガジェットを受け取っている中、爆発的な身体強化を施されている。

**Comment by mc-Genius** [comment]
私にいい考えがある。
