### ISSUE TITLE
【T.利央 2040】の説明文みたいなの

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#209]
T.利央 2040の説明文を書こうと思ってるのですが、牡蠣の文章以外に付け加えてほしいものとかありますか？

###### T.利央 2040

```
エーテルにより、不可解に通信技術の発達した都市
世界全体では、通信技術は単体のスマートフォンでも一秒間に1Tという驚異的な速度を実現している。
世界には多くの都市が存在し、【東京タワー】【東京駅】【渋谷】【新宿】【秋葉原】【利央】など単独で一つの名称の街も多く存在している。
だが、この世界全体では、この街全体を【T.利央】という名前で総称すると確定している。

デュエルモンスターズの精霊を操る組織やシンフォギアなどを操る独自組織も多く存在しており、街全体が謎に包まれている
```

忙しいかもですが、確認の方よろしくおねがいします。

**Comment by mc-Genius** [comment]
再度連絡します。確認したら、お手数かけますが @lupan2525 @gooozudo は確認メッセージ。
追加してほしいものがあれば、追加要請をお願いします。

---
期日は
**平成31年4月5日**
まででお願いします

**Comment by gooozudo** [comment]
私は大丈夫です

**Comment by mc-Genius** [comment]
@gooozudo 了解です。ありがとうございます。

**Comment by lupan2525** [comment]
確認しました、追加はありません

**Comment by mc-Genius** [comment]
@lupan2525 了解です。別途になりますが
@lupan2525 @gooozudo は #210 の方も確認お願いします。

二人が確認完了しましたら、最終確認者はクローズお願いします。

**Comment by mc-Genius** [comment]
ねぇ、ほんとに二人ともこれでいいの
私、下記のところ、牡蠣に間違えてしてる

牡蠣の画像貼り付けるよ？

**Comment by gooozudo** [comment]
やってみやがれ

**Comment by mc-Genius** [comment]
わかった。GM紹介のポチの画像は
牡蠣にしてやろう
