### ISSUE TITLE
C・デッキ作成依頼

### ISSUE THREAD

**Issue by gooozudo** [stcg-document/STCG-Dev-Page#21]
◆重要カード
C・ドラゴン

■対象相手
おもひかねさん

**Comment by gooozudo** [comment]
マシュさんから頂きました。
ありがとうございました。

**Comment by mc-Genius** [comment]
GitHubの方に上がっていません。
再度、GitHub上げて、手順を守った上でクローズしてください。

Discordでのファイルやり取りは基本無しでお願いします。

**Comment by Mashumac** [comment]
デッキ作成依頼の「Ｃデッキ」を作成しました。closeも完了しました。
