### ISSUE TITLE
【祝杯】T.利央の一期終了

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#220]
無事 @gooozudo @lupan2525 の活躍でS.T.C.G. 「Cloud編」は終了を迎えることが出来ました。

この場を借りて皆様にお礼申し上げます。

二人以外にも数多くの皆様の協力・モチベーションあっての素晴らしいストーリーの完成だと思います。

これからも「T.利央編」は続き、次回は「オレイカルコスの結界編」へとステージを移します。
これ移行の皆様の活躍を心から願うとともに
今までの皆様のご活躍に心からお礼申し上げます。

**Comment by gooozudo** [comment]
とりあえず約1か月間お疲れさまでした、そしてもけもけの技術面やセッションでのサポート、ルパンさんのストーリー提案など、色んな人に支えられて良い形で第一部を締められたと思います、ありがとうございました。

少々急ぎの作成でストーリーの不備など、NPCをやって頂いた人達には迷惑を沢山かけてしまうような事が多々ありましたが、1か月の休養期間の中でその辺も話し合って行けたらなと思っています。

改めてですがここまで協力して頂いてありがとうございました！
これからもよろしくお願いしますね。

PS.ルパンニキはもう少し自分に自信を持ってもいいと思います。
