### ISSUE TITLE
三騎士のカードについて

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#24]
#18 について、聞きたいのですが
こちらカードイラストは原作のような名も無き龍の絵柄でよいのですか？

それとも騎士状態の三人が封印されてる感じが理想ですか？

**Comment by gooozudo** [comment]
封印されているイメージでお願いしたいです

**Comment by mc-Genius** [comment]
ポチを封印ですね

**Comment by mc-Genius** [comment]
作成物を把握したので、クローズします。
