### ISSUE TITLE
セッションでの利用カードについて

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#3]
ポチのシンクロ次元で利用する名もなき竜のカードは原作効果のカードを作成したほうがいいですか？
作成したほうがいい場合、どれを作成すればいいですか？

- カード名
  - ティマイオスの眼
  -  ヘルモスの爪
  -  クリティウスの牙

**Comment by gooozudo** [comment]
俺がルールだ。

**Comment by mc-Genius** [comment]
カード作成は必要ないという認識をします。
よければ、クローズしてください。

**Comment by gooozudo** [comment]
嘘作ってほしいカードあります馬鹿

**Comment by mc-Genius** [comment]
特に何もなさそうなので、クローズします。
