### ISSUE TITLE
BGM追加依頼

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#30]
ファンタシースターオンライン2 オリジナルサウンドトラック Vol. 6の全部の曲を追加してください

**Comment by gooozudo** [comment]
いやです

**Comment by mc-Genius** [comment]
必要なさそうなのでクローズします。

**Comment by mc-Genius** [comment]
必要ありそうなので、サイドオープンします。
Disk1 と Disk2 のお願いします。

**Comment by mc-Genius** [comment]
終了を確認しました。クローズします
