### ISSUE TITLE
BGMの追加依頼

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#31]
第3次スーパーロボット大戦Z 時獄篇&天獄篇 オリジナルサウンドトラックをDisk.1からDisk.7まで追加してください。

**Comment by mc-Genius** [comment]
Disk.4を最優先にお願いします。

**Comment by lupan2525** [comment]
お疲れ様ですLupanですDisk.4ですね現在の作業が終わり次第作業に入ります

**Comment by lupan2525** [comment]
お疲れ様ですLupanです、Disk.4のBGM追加しました確認をお願いします、
ほかのDiskは随時入れていきますのでよろしくお願いします
