### ISSUE TITLE
BGMの追加

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#32]
無双☆スターズ ORIGINAL SOUNDTRACK CD

-  カジノ·序盤 All-In! -Starlet Mix-
-  カジノ·メイン All-In! -Stars Mix-
-  カジノ·終盤 All-In! -Stars Mix GT-
-  東京駅&銀座錬瓦街·序盤 黒蝶 -Starlet Mix-.
-  東京駅&銀座錬瓦街·メイン 黒蝶 -Stars Mix-
-  東京駅&銀座錬瓦街·終盤 黒蝶 -Stars Mix GT-

を追加してください

**Comment by gooozudo** [comment]
おわったぞハゲ
