### ISSUE TITLE
エクシーズ次元の設定・シナリオ

### ISSUE THREAD

**Issue by Mashumac** [stcg-document/STCG-Dev-Page#34]
・目的はこのエクシーズ次元で～～～～～
・１日に１度ハートランドの好きな場所に移動してロールをしてもらいます。
・《食糧》１日に１度参加プレイヤー、主要メンバー、捕虜、客、保護した人、ペットの数×100消費します。初期値は3000
食糧は通貨として使用する場合もあります。
・《電力》１日に１度電力を100消費します。決闘盤の充電でも消費されます。新たな設備やアイテムの入手次第でまた更に消費される場合があります。初期値は3000

【探索可能エリア】

・ハートランド商店街
食料品や医療品が手に入りやすい場所です。
物資が眠ってる場所ということもあり避難した住人やそれを狩ろうとするアカデミアもよく現れる場所です。

・ハートランドスクール
避難した住人が拠点にしていることが多いです。だからこそ狙われやすい場所でもあります。
住人が立ち寄りやすい場所なので情報交換や物資の交換が行える場合があります。

・ハートランド広場
かつて色んな人達がここでデュエルを楽しんでいた場所です。
イベントが発生しやすい場所です。
見通しが良すぎるため住人はこの辺りを避けるのでアカデミアもこの辺りはあまり現れません。
近くにカードショップがあります。
４日目に盗賊がここに現れ、カードショップのカード全てを奪っていきます。

・破壊され尽くした街
瓦礫ばかりです。
デニスの地下室があります。
掘り出し物が落ちてる場合があります。

・アカデミア拠点
アカデミアがエクシーズ次元に作った拠点です。
敵の本拠地で非常に危険な場所です。

・山
どこかに秘密基地があります。
食糧採取が１人１回可能で1d6×100の食糧を手に入れることが可能です。
たまに熊や狼や猪や鹿や兎など野生動物が現れます。
２回目に訪れると滝を発見して修行が可能です。

【隠しエリア】

・秘密基地
アレンの秘密基地です。彼の貴重品はこの辺りに隠されています。
敵は必ず現れない安全地帯です。

・デニスの地下室
デニス・マックフィールドが拠点にしていた地下室です。
彼の正体が暴かれた後に入ることが可能です。

・盗賊団の基地
アカデミアが街をメチャクチャにした時に現れる火事場泥棒のグループの基地です。
裏でアカデミアの幹部と繋がっていて住人の位置を密告することで自分達の安全を確保しています。

・アカデミア牢に繋がる通路
アカデミアの牢獄に繋がっています。捕虜は皆ここに入れられます。

【アジトに滞在】

・探索を行わずにレジスタンスアジトに滞在することも可能です。
滞在した場合アジトで可能な事

１）：滞在しているキャラクターと会話・デュエルが可能です。
そのデュエルは１日に１度のみ挑戦をすることができます。
デュエルに勝利した場合、そのキャラクターのデッキの中身からランダムに１枚カードをプレゼントされます。

２）：偵察隊隊長ドロワが帰還し、他の滞在したキャラと同じく会話が可能です。ドロワは各地を回って情報を集めたりしているので色々教えてくれるかもしれません。
ドロワは好感度を上げることのできないキャラクターです。

３）：マシュ先生から訓練を受けることが可能です。訓練内容は「生き延びる知識」「デュエルの訓練」「リアルファイトの訓練」の３種類です。デュエルの訓練の後は報酬でカードを入手できます。
各訓練は１セッションに１回しか行われないので複数のプレイヤーが受けたい場合は同時に話しかけるロールをしてください。

４）：ゴーシュの戦利品分配が行われることがあります。(2日に1回)
戦利品のカードをシャッフルした後、1d6でダイスを振って出た目の数だけランタムに入手可能です。
【デュエルについて】

・決闘盤は充電式です。電力を100まで貯めることが可能です。
通常の決闘は電力を30消費、質量を持った決闘は60消費、ロールでモンスターを実体化召喚するのに20消費します。

・決闘は精神力を消耗します。決闘でライフを100削られる毎に精神力がマイナス１されます。
質量を持った決闘でライフを削られる場合、同時にＨＰもマイナスされます。

・エクストラデッキに入れることができるカード枚数は「デュエリストレベル」に比例します。
デュエリストレベルが３の場合はエクストラデッキの上限は３枚、デュエリストレベルが５の場合はエクストラデッキの上限は５枚。

・デュエリストレベルはデュエルをすることで経験値が貯まってレベルアップします。
一戦でデュエリストレベル×10の経験値を入手でき、勝利することでその倍の経験値を得ることができます。
例えば決闘レベル７のユートに特定の条件で勝利した場合
《決闘レベルポイント:70》《勝利ボーナス:70》《ジャストキルボーナス:10》《スキル未設定ボーナス:20》《合計:170経験値獲得》
こういう経験値の獲得処理になります。
決闘レベル1→2「必要値50」
決闘レベル2→3「必要値80」
決闘レベル3→4「必要値100」
決闘レベル4→5「必要値120」
決闘レベル5→6「必要値150」
決闘レベル6→7「必要値200」
決闘レベル7→8「必要値250」
決闘レベル8→9「必要値300」
これ以上は全て「必要値300」

・アイテム「EXPブースター」を決闘前に使用した場合、合計経験値の更に倍の経験値を獲得できます。これはロールで入手したり、セッションを休んだ人の補償としてプレゼントされることで手に入れることが可能です。
・レジスタンスの皆もデュエルが好きです。デュエルをすることで好感度を上げることが可能です。

・アカデミア兵士は皆支給されたデッキを使用します。そのカードはアカデミアにロックされているため使用は不可能です。彼らもデッキからカードを抜く事は不可能です。しかし、兵士も決闘者です。デッキをアレンジしてデッキ枚数を増やしたりすることがあります。
その兵士を捕獲や気絶や殺害することでそのカードを奪うことが可能です。

・アカデミアとの決闘に敗れた場合、ＨＰが０になった場合戦死してしまいます。
ＨＰが残った状態で敗北した場合はカード化されてしまいます。

・サレンダーをした場合、戦死したりカード化されることはありません。ですが相手の捕虜になってしまいます。
盗賊の捕虜になった女性キャラクターは３日経過することで、行方不明(死亡扱い)となります。
幹部のキース・ハワードを倒している場合は行方不明にならず時間が経過しても捕虜のままとなります。

・デュエルを中断・切断した場合、２つの選択肢があります。
１）逃走を図る。
２）サレンダーと同じ扱いとして捕虜になる。
逃走は俊敏性ダイスで成功か負傷か死亡となってしまいます。
成功はそのまま逃走、ダイスを失敗した場合、その対戦相手のデッキからデッキ・EXデッキのモンスターの中で最も攻撃力の高いモンスターでＨＰにダイレクトアタックを受けてしまいます。
負傷してもＨＰが残れば逃げ切ることは可能です。
そのままＨＰが０になった場合は死亡してしまいます。

【カード化・捕虜について】

・カード化されたプレイヤーは２つの選択肢があります。
①生存を諦め死亡する。
②生存に賭け待機する。
死亡はそのまま死亡です。
待機をした場合、そのカード化させた敵を見つけだしてデュエルで勝利することでカード化した仲間を手に入れることができます。

・カード化の解除方法はアカデミアの幹部の科学者がその手段を持っているらしいです。

・アカデミアの捕虜になったプレイヤーは１日経過するごとに拷問を受けてライフを10消費します。
アカデミアに潜入したり、壊滅させたり、奪還することでその捕虜になったキャラクターを奪い返すことが可能です。
捕虜になったプレイヤーは自殺が可能です。
特別なアイテムを持っている場合脱出ロールをすることも可能です。

・盗賊団の捕虜になったプレイヤーは拷問等はされません。
ですがアカデミアに付き出される場合があります。
女性キャラクターが捕虜になって３日経過した場合、そのキャラクターは行方不明(死亡扱い)となります。

・敵の科学者の捕虜になった場合、１日姿を眩ませます。そのご戻って来ますが……？

【リアルファイト】
・アカデミア、盗賊、モンスター等とリアルファイトする場面があります。
攻撃順は俊敏の高いキャラクターから順番に、俊敏が同じキャラクターがいる場合は優先度は「プレイヤー＞味方NPC＞敵」となっています。プレイヤー同士でも俊敏が同じな場合は相談して行動順を決めることが可能です。
全てのNPCはステータスが設定されています。
モンスターは攻撃力/100が力、レベルと俊敏が比例、守備力/100がＨＰとなっています。
・通常攻撃は1d6でダイスを振り、それにステータスの力が加算されたダメージを相手に与えます。
・戦闘前、戦闘中にアイテムの使用タイミングがあります。
例:戦闘前に「投石」で先制攻撃
例:戦闘中に「薬」で回復

【登場人物】

味方陣営

・Ⅲ（ミハエル・アークライト）
・Ⅳ（トーマス・アークライト）
・Ⅴ（クリストファー・アークライト）
・トロン
・神代凌牙
・神代璃緒
・ギラグ
・アリト
・ミザエル
・ドルべ
・真月零

敵陣営

・エド・フェニックス（総司令官）
・オブライエン（傭兵）
・丸藤亮（浮浪の死神）
・コザッキー（科学者）
・オベリスク・フォース
・ラー
・オシリス

【キャラクターの好感度】
・キャラクターの好感度は最大100まであります。
・好感度を10上げる毎にキャラはプレイヤーにプレゼントをしてくれます。

【基本的な上げ方】
決闘をする ＋２
決闘で勝利 ＋３
決闘で敗北 ＋１
キャラクターが決闘に参戦してる中でエースモンスターを召喚 ＋１
会話をする ＋１
出掛けた先で会う ＋３
プレゼント ＋３(好みの場合倍)
一緒に行動 ＋５

【上げた状態で発生するイベント】

・好感度２５
イベントが無いキャラに限り、誘うロールをすることでそのキャラクターが同じ場所に来てくれる
Ⅲ・Ⅳ・Ⅴは好感度関係無しに誘えば来てくれる

・好感度５０
エースカードをくれる

・好感度７５
プレイヤーが死の危険に迫った場合、イベントが無いキャラに限り助けに来てくれる

・好感度１００
？？？

【プレゼント】

・Ⅲ
10.食料1000
20.応急キット+30
30.《先史遺産クリスタル・エイリアン》
40.ロープ
50.Ⅲの鎧
60.《星遺物を巡る戦い》
70.手作り弁当
80.
90.《リビングデッドの呼び声》
100.《》

・Ⅳ（トーマス・アークライト）

10.《マーシャリング》
20.変装ローブ
30.
40.《ギミックパペット-ヘブンズ・ストリングス》
50.
60.
70.《手札抹殺》
80.
90.
100.

・Ⅴ
10.《RUM-アージェント・カオス・フォース》
20.ハーモニカ
30.キャラメル
40.
50.《CNo.5 》
60.食料2000
70.アカデミア・サーチャー
80.《》
90.
100.《》

・神代凌牙
10.《RUM-バリアンズ・フォース》
20.
30.携帯用充電器+10
40.《リヴァイエール》
50.ダッシュブーツ
60.携帯用充電器+15
70.《》
80.
90.携帯用充電器+15
100.《No.101 S・H・Ark Night》

・神代リオ
10.《RUM-バリアンズ・フォース》
20.隠密ローブ
30.
40.《墓地墓地の恨み》
50.お守りのリトル・フェアリー
60.《》
70.隠密ローブ
80.
90.《》
100.《CX》

・ギラグ
10.《RUM-バリアンズ・フォース》
20.
30.
40.《ファイアー・ハンド》
50.
60.
70.《アイス・ハンド》
80.
90.
100.《》

・アリト
10.《RUM-バリアンズ・フォース》
20.
30.
40.《BK ペイル》
50.
60.
70.《》
80.
90.
100.

・ミザエル
10.《RUM-バリアンズ・フォース》
20.
30.
40.
50.
60.
70.《妖精竜？》
80.
90.
100.

・ドルベ
10.
20.
30.
40.
50.
60.
70.同胞の絆
80.
90.
100.

・真月零
10.
20.
30.
40.
50.
60.
70.
80.
90.
100.

【アイテムリスト】

・食料
全てのキャラクターとプレイヤーは１日に合計「食料100」を消費します。

・応急キット
出掛け先でも使用できる回復薬です。ライフは最大値以上にはなりません。

・ロープ
汎用性が高いロープです。
高い場所から降りたり相手を捕縛したりできます。

・変装道具
一般市民Ａに化けることが可能です。化けた状態で正体がバレていない仲間に接触した場合好感度は0で接せられます。
このアイテムは消費しません。

・ハーモニカ
1日に1度のみ演奏が可能です。
その場にいる皆に綺麗な音色を聴かせて落ち着かせます。
このアイテムは消費しません。
精神力+10

・楽譜
ハーモニカの腕が上がります。
ハーモニカを使用した時に回復する精神力が50になります。

・キャラメル
口の中で優しい甘味が広がります。精神状態がそのセッション中減りません。
誰かにプレゼントした場合、上昇する好感度は２倍になります。
満腹度+10

・隠密ローブ
布を被って隠れることができます。不自然な場所で使用した場合は見破られます。１人用です。
このアイテムは消費しません。

・手作り弁当
簡素な食料と違って温かい食事が出掛け先でも食べられます。
満腹度+100 精神力+100

・ユートのバンダナ
①ライフが2000以下になったドローフェイズに発動する。
通常ドローの枚数が２枚になる。

・黒崎隼のバンダナ
①ライフが2000以下になったメインフェイズに発動できる。
エクシーズモンスターは相手フィールドの特殊召喚されたモンスター全てに１回ずつ攻撃できる。

・カイトのバンダナ
①ライフが2000以下になったドローフェイズに発動できる。
自分の墓地のモンスター１体を選択し、その同名モンスター全てを墓地から表側守備表示で特殊召喚する。

・ダッシュブーツ
必ず戦闘から逃げれる
ロールで何かしら使える

・お守りのリトル・フェアリー
死亡・カード化した場合これを消費することでレジスタンス基地で目を覚ます

**Comment by mc-Genius** [comment]
見やすい感じに変更したんで、ここいらないのでクローズします。
