### ISSUE TITLE
【カード追加】古代の機械参頭猟犬

### ISSUE THREAD

**Issue by Mashumac** [stcg-document/STCG-Dev-Page#39]
◆カード名:古代の機械参頭猟犬
◆分類:アニメカード
◆カードID:Unknown
□カードタイプ：モンスターカード 
□ カード種類 ： 融合
❏カード効果  :「古代の機械猟犬」＋「古代の機械猟犬」＋「古代の機械猟犬」 
または「古代の機械猟犬」＋「古代の機械双頭猟犬」 
①：このカードは１度のバトルフェイズ中に３回までモンスターに攻撃できる。 
②：このカードが攻撃する場合のダメージステップ終了時まで、相手は魔法・罠カードを発動できない。

**Comment by mc-Genius** [comment]
終わってないからクローズしないで（）

クローズするなら、理由の書き込みをお願いします。

**Comment by mc-Genius** [comment]
作成完了しました。クローズします。
