### ISSUE TITLE
遊戯王ZEXALサントラ 創造龍ヌメロン・ドラゴン

### ISSUE THREAD

**Issue by Mashumac** [stcg-document/STCG-Dev-Page#43]
■ 遊☆戯☆王5D's
■ 動画URL
https://www.youtube.com/watch?v=7m0AO3tvgeM

**Comment by mc-Genius** [comment]
結構 @lupan2525 さんが別作業で苦戦してるみたいなので @gooozudo さん、申し訳ないですが、お願いします。

**Comment by gooozudo** [comment]
追加しました、クローズします。
