### ISSUE TITLE
【シンクロ次元でのテーマデッキ】

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#50]
##### シンクロ次元ボステーマ
---
- BF
- 魔妖
- レッドデーモンズ
---
##### シンクロ主要テーマ
---
- ドラグニティ
- Xセイバー(仮)
- アンデアイズ
- レッドアイズ(EXは１、２枚のリンクのみ)
- ジャンク・ウォリアー

**Comment by gooozudo** [comment]
色々追加しました

**Comment by gooozudo** [comment]
確認しやした、クローズします。
