### ISSUE TITLE
レッドデーモンズ【デッキ依頼】

### ISSUE THREAD

**Issue by gooozudo** [stcg-document/STCG-Dev-Page#51]
◆重要カード
琰魔竜王 レッド・デーモン・カラミティ

◆期日
2019年3月23日

◆対戦相手
あかりorヒユキ

**Comment by mc-Genius** [comment]
担当します。
確認しましたが、マイルストーンのデッキ作成依頼に必ず入れてください

**Comment by gooozudo** [comment]
すみませんでした許してください

**Comment by mc-Genius** [comment]
だめです。ポチ叩きます。

**Comment by mc-Genius** [comment]
コミットして忘れてました。クローズします。
