### ISSUE TITLE
【カード化について】

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#53]
PL・NPC関係なくカード化します。
---
- オレイカルコスの結界を使用した /  された決闘で敗北したとき
- 闇のゲームで敗北したとき
- ラスボスが製造したカードを魂に幽閉する機械を使用されたとき

#### 捕まったプレイヤー
---
一部システムを #42 を流用します。

解除方法
- ラスボスを倒すことでカード化を解除可能
- カード化された人は二人まで、シンクロ次元でのみ 使用できる別キャラを作成することが可能です。ただし、そのキャラクターはシンクロ次元から初期のPLキャラクターがカード化から解除されたとき、元の世界に帰還することになります。

**Comment by gooozudo** [comment]
確認しやした、クローズします。
