### ISSUE TITLE
【シンクロ次元の舞台について】

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#54]
■場所：
利央町(りおうちょう)

Dホイールについて：
ライディングデュエルは行いませんが、デュエルディスクが装着可能なバイクが存在しており、それをDホイールと呼称しています。

シンクロモンスター：
みんなが誰でも持っているカードです。

シンクロ次元の人々：
シンクロ次元にいることは自覚してない。
認識している組織も存在している。

デュエルはどんな位置にありますか？：
Eスポーツのような感じです。オリンピックよりは知名度が高い。

**Comment by gooozudo** [comment]
確認しやした、クローズします。
