### ISSUE TITLE
【カードリスト】

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#63]
モンスターカード
---
- サイバースクアンタムドラゴン(あかり用)
- 傀儡虫
- ハネクリボー
- ハネクリボー LV10(ハネクリボーを入手した人に渡す用)
- 竜騎士ブラック・マジシャン(魔理沙用)

魔法カード
---
- 団結の力
- 同胞の絆
- ティマイオスの眼(魔理沙用)
- ヘルモスの爪
- クリティウスの牙
- 進化する翼(ハネクリボーを入手した人に渡す用)
- 炎舞-「天機」(ブロリー用)

罠カード
---
- 魔女の一撃
- スリーカード

**Comment by gooozudo** [comment]
カードリスト更新しました。

**Comment by mc-Genius** [comment]
えらい

**Comment by gooozudo** [comment]
竜騎士ブラック・マジシャンを追加しました

**Comment by gooozudo** [comment]
確認しやした、クローズします。
