### ISSUE TITLE
【最重要課題】必ず確認を！

### ISSUE THREAD

**Issue by mc-Genius** [stcg-document/STCG-Dev-Page#64]
##### それが下記の通りです。またこの疑問は非常に良くない傾向にあります。速球に解決策を出し、解決させる必要があります
---
- 自分のキャラクターがいない次元なら自分は何もやらない。参加しなくていい
- 自分のキャラがあまり出ないセッションであれば、参加する必要がない。
- 自分のキャラに出番がほしい
---
##### 各次元担当者は、その次元にいないPCに対して、どのような補填をしていくようになるかを最重要課題のラベルを入れ、【Issues】に新たに私宛に【Submit new issues】つまりは、新規作成してください。また、急遽になりますが、下記の期限までにお願いいたします。
---
## 2019年3月21日
---
備考：Markdown記法についての詳しい書き方は下記をクリックしてください
　　　　　→   **[Markdownチートシート](https://github.com/stcg-document/STCG-Dev-Page/blob/master/STCG%20Document/MD/Markdown%E8%A8%98%E6%B3%95%20%E3%83%81%E3%83%BC%E3%83%88%E3%82%B7%E3%83%BC%E3%83%88.md)**

**Comment by mc-Genius** [comment]
対処方法が一応、思いつきました。
本日帰宅が午前2時位になると思うので、その後、「Issues」に追加します。

#64 は他の方から代案が出る可能性があるので、ひとまずクローズしません。

**Comment by Mashumac** [comment]
案①：カードをもっとバラ巻く

今回の章はカードの入手の難易度が上がっているため、そのセッションに参加した時の得る物や戦利品といったものが期待し辛くいという問題もあると思います。
「参加してよかった」「来てよかった」というお得感を形にして、PCに与えることも重要ではないかと思います。

また、新規カードが少な目な事もあってかデュエルが皆決まりきった動きしかしないのも問題であると思っています。
今までのSDでデッキを改良していく形式の頃はセッション外でもセッション用デッキを用いて皆でフリーデュエルをしていましたが、最近はOCG環境ばかりです。
決闘者目線でもやはりデッキは皆変化があった方が色んな楽しみが発生しやすいと思っています。

まとめると「カード入手のお得感」「デュエルした時の目新しい楽しさ」のためにもカードのバラ巻きはもっとやった方がいいと考えております。

※現在はストラクチャーデッキを制作して配るシステムができているというのは理解した上の発言です。現状を打破しようとGMは既に案を練っていらしたと思われますが、今回はあえてPL目線で感じていた感想を元に書かせて頂きました。

**Comment by Mashumac** [comment]
案②：【システム案】PLの精霊化

PLを精霊化させて各次元に旅立った皆に憑依させるというのはいかがでしょう？（例：アテム・アストラル）
メリットが３つあります。（今週の３つ）


①：PLがバラけれなくなる。
PL人数は合計10人ほどです。更に単独行動を好む人や主張が強めの方もそれなりにいらっしゃいます。
どどんとふは１つですのでPL達がバラバラに行動していては1人1人の時間が確実に減ってしまい、暇な時間と感じる人も多数現れるかと思います。
ですのでPLをまとめてしまうことで単独行動をできなくし、個人ロールの時間をカットさせることで全員が長くロールできるようになるので退屈な時間が減るというのが１つのメリットです。

②：主役がハッキリする。
その次元で活躍するというのが霊体のPLでなく、実体のPLということが皆の目線でハッキリしているのでプレイヤーの贔屓に説得力ができます。
遊戯のようにPLのマインドシャッフルができるという設定にすることで霊体の人も活躍させることができ、時には本体の方が欠席された場合霊体の1人が受肉してセッションに参加できるのでその人にお得感を与えることができると思います。

③：少数精鋭になるのでGM歴が浅い我々でもシナリオが動かしやすい
こちらはタイトルの通りです。精霊というのは遊戯王本編でもそうですが、非常に使い勝手のいいフワフワした便利な設定です。
場合によっては受肉させたり、霊体に戦わせたり、本体が力尽きたら中の人と人格を入れ替えるという残機制にしたり、霊体の人はモンスターと会話できたり、色んなオリジナル設定で料理できます。


以上の３つの理由でこちらを提案させて頂きます。問題点３つを抑えた案だと個人的に見解しております。

**Comment by mc-Genius** [comment]
> 案①についてはOCGで現状は結構です。
> 以前と違い、デッキ自体 ほぼ完成されたものを渡しており、私が基本、お渡ししているカードは
> 
> -  現状、プレイヤーたちがサイドデッキに入れていたカード
> - その後、新規カードなどが出たとき、ほしいと依頼されたカード

---

> 上記がほとんどです。故にプレイヤーたちのデッキは今現在、ほぼ完成されていまs。
> そのため、スターターデッキを入れた際に、全員のデッキバランスにより、デッキレベルが大きく変わる場合があります。そのため、案①に関しては、実行するにしてもかなり苦肉の策です。

---

> 案② #66と重複箇所があるので、一部省きます。
> 案②の①についてですが、PLがバラけなくなるという案については、正直なんとも言えません。
> みなさんがどう考えてるか知りませんが、全員なかよくみんなで一緒に行動しましょう = TRPG
> ではありません。一人の何気なくした行動が、全員に影響を及ぼし、後に皆の影響になるというのもTRPGの一つの形です。
> 
> まず頭から、団体行動 = TRPGを排除してください。
> 
> それを念頭に置いた上でですが、#66 の憑依覚醒とほぼ同意義なので一応、案としては賛成ですが、詳細を私の方でもあげ、再検討する必要があります

---

> 結論から言います。手段としてはいいと思いますが、採用理由について、大量の懸念点があります。
> 
> ②：主役がハッキリする。
> これについてですが、まず 「お前は一体何を言ってるんだ？」というのが第一の発言です。
> TTCGの全盛期の頃から私の方から言っていますが、あくまでTRPGは「誰でも主役になれる。誰もが主役」というのが一番のゲームです。
> 
> 理論上や机上の空論になる部分はわかりますが、主役を一人に絞る必要は余りありません。
> あくまで、一人を中心にそのセッションの間は話を勧め、その中からPLのロールによって、誰もが主役になれる。というのが一番の理想です。
> 
> TTCGのいづきのブルーアイズ戦でマシュが主役になったように主役というのは過半数イレギュラーで発生するものです。
> それをGM側が主役をはっきりさせるのは正直言って言語道断です。

---

> ③：少数精鋭になるのでGM歴が浅い我々でもシナリオが動かしやすい
> これですが、考え方としてはかなりありだと思います。
> 私としても意見には賛成ですが、懸念点があります。
> 
> 本体が尽きたら霊体と交代とありますが、本体のHPが尽きたら交代というイメージですか？
> もしそうなのであれば、その状況になることは戦闘を一時的に撤廃している、及び戦闘で過半数は逃げ腰となっているため、この状況になることはありえないでしょう。
> 
> 残機制という案ですが、これについては結果としてなりうる案の一つでしかありません。
> キャラクターロストのある「エクシーズ次元」「シンクロ次元」には適切な対処のように思えますが、全体の次元を通してでは、あまり適切な対処とは言えません。
> 
> 全体に利用できるプランニングが必要になるでしょう。

---

> 
> 上記の意見をもとに今現在、意見があまりはっきりと定まっていないというのは判断ができます。
> よって、まずはDiscordの方に記述したプランニングシート・タイムチャートの2つをなるべく早く完成させましょう。
> 
> これについては私が聞きながら話すということになるので、 @gooozudo の次元で @mc-Genius が作成したプランニングシートを元に、埋め込むべき内容を全員しっかりと把握して、聞かれたときにすぐに答えられるようにしましょう。
> 
> @stcg-document/stcg-dev-team 全体の課題です。

**Comment by mc-Genius** [comment]
及び言うならば、今現在OCGはほぼ更新ラッシュです。
セッションのデュエルを大量のほうが分母を多くというのは、恐らく無理です。
そして、そこは飽くまで結果によってついてくる目標ですので、あまり囚われないことをおすすめします。

メイン目標と副効果の判別はしっかりと認識しましょう。

**Comment by mc-Genius** [comment]
及び、全体の課題として、最優先課題はプランニングシートの確認とGMの方で判断します。
一時的にクローズします。
プランニングシートを @lupan2525 以外がかけ次第、再度オープンします。
